stages:
  - install
  - build

variables:
  npm_config_cache: '$CI_PROJECT_DIR/.npm'

before_script:
  - VERSION=${CI_BUILD_REF_NAME:8:${#CI_BUILD_REF_NAME}}
  - PACK_FILE_PATH=/Users/ovo/Documents/dist/$VERSION
  - VERSION_FILE_PATH=/Users/ovo/Documents/version/$VERSION

job_install:
  stage: install
  cache:
    paths:
      - node_modules/
  script:
    - rm -f package-lock.json
    - export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1
    - npm install --registry https://registry.npm.taobao.org;

job_build:
  stage: build
  cache:
    paths:
      - node_modules/
    policy: pull
  script:
    - npm run build;
    - echo 'ref_name:' ${CI_BUILD_REF_NAME} > dist/version
    - echo 'commit_id:' ${CI_COMMIT_SHA} >> dist/version
    - echo 'project_dir:' ${CI_PROJECT_DIR} >> dist/version
    - echo 'date:' $(date) >> dist/version
    - rm -rf $PACK_FILE_PATH/packagetest
    - rm -f $VERSION_FILE_PATH/packagetest
    - mv dist packagetest
    - mv packagetest $PACK_FILE_PATH
    - echo 'packagetest' ${CI_BUILD_REF_NAME} ${CI_COMMIT_SHA} > $VERSION_FILE_PATH/packagetest